# TODO: review all of these

modLoader="javafml"
loaderVersion="[24,)"
issueTrackerURL="https://github.com/gegy1000/LLibrary/issues"
displayURL="https://github.com/gegy1000/LLibrary"
authors="gegy1000"

[[mods]]
modId="llibrary"
version="${file.jarVersion}"
displayName="LLibrary"
updateJSONURL="http://myurl.me/"
description='''
'''

[[dependencies.llibrary]]
  modId="forge"
  mandatory=true
  versionRange="[24,)"
  side="BOTH"
