# TODO: review all of these

modLoader="javafml"
loaderVersion="[24,)"
issueTrackerURL="https://github.com/gegy1000/LLibrary/issues"
displayURL="https://github.com/gegy1000/LLibrary"
logoFile="llibrary.png"
credits="LLibrary Contributors: iLexiconn, pau101, BobMowzie, FiskFille, TheCyberBrick, Glen_AA"
authors="gegy1000"

[[mods]]
modId="llibrary-animation"
version="${file.jarVersion}"
displayName="LLibrary: Animation"
updateJSONURL="http://myurl.me/"
description='''
'''

[[dependencies.llibrary-animation]]
  modId="forge"
  mandatory=true
  versionRange="[24,)"
  side="BOTH"
